### ISSUE TITLE
Работа библиотеки на .net core 

### ISSUE THREAD

**Issue by svver** [xeltan/EsiaNET#1]
Добрый день! Подскажите пожалуйста, будет ли библиотека работать на .net core и, если нет, возможно ли ее перевести на .net core в принципе?

**Comment by xeltan** [comment]
Добрый день! На .net core не работает, но будет переведена в скором времени - ближе к концу года или начале следующего

**Comment by xeltan** [comment]
Support .NET Core 3.1
