### ISSUE TITLE
EsiaCertificate

### ISSUE THREAD

**Issue by slartus** [xeltan/EsiaNET#2]
> // Action должен вернуть сертификат ЕСИА тестовый или рабочий. В данном примере ищем сертификат по его пути, указанном в конфигурационном файле
>         () => new X509Certificate2(WebConfigurationManager.AppSettings["EsiaCertFile"]))

какой сертификат надо вернуть? 

в тестовую среду к организации загружен сертификат, выгружаю его, получаю **name.cer** - возвращаю путь к нему. 
**VerifyToken** возвращает **false**

**Comment by xeltan** [comment]
Здесь нужен сертификат ЕСИА (тестовый или рабочий), а не вашей организации. Эти сертификаты можно запросить через техподдержку

**Comment by slartus** [comment]
спасибо
