### ISSUE TITLE
Не принимает scope для полной информации

### ISSUE THREAD

**Issue by slartus** [xeltan/EsiaNET#3]
при попытке указать scope **http://esia.gosuslugi.ru/usr_inf** esia пишет "ошибка авторизации".
как получить инфу по orgs? вроде на них и scope  не нужен какой-то особенный, но esia возвращает 403

**Comment by xeltan** [comment]
вроде бы ЕСИА сейчас не принимает полный scope (а этот именно полный). А на какие-то ваши другие scope ЕСИА выдает правильные результаты? Чтобы получить orgs нужен тоже соответствующий скоуп (и разрешен ли он вам). Можно указать несколько scope через пробел

**Comment by slartus** [comment]
fullname id_doc openid email,  и др. короткие scope принимает. а вот scope для orgs не нашел в документации. хотел по полному получить.  и вот оказывается, полные не принимает. хотя документацию скинули недавно. спасибо.

**Comment by slartus** [comment]
usr_org - scope для организаций пользователя
