### ISSUE TITLE
Работа библиотеки под .net Core 3.1

### ISSUE THREAD

**Issue by tihomirov71** [xeltan/EsiaNET#5]
Работает ли библиотека под .net Core 3.1?
Если нет, то планируется ли обновление?

**Comment by xeltan** [comment]
Не работает. Планируется поддержка .net core к июню

**Comment by tihomirov71** [comment]
А что с работой под ГОСТ?

**Comment by xeltan** [comment]
Криптография отдельная часть библиотеки и ее можно заменить. Сейчас достаточно вернуть нужный сертификат (ГОСТ или любой другой), то есть для формирования подписи при обращении к ЕСИА этого достаточно (как в примере в документации).
Вопрос про проверку ответа подлинности access token полученного от ЕСИА. Вот тут сейчас нужно подменить SignProvider на кастомный, так как в дефолтном идет проверка по RSA (см. https://github.com/xeltan/EsiaNET/blob/master/EsiaNET/DefaultSignProvider.cs). То есть нужно в классе реализовать интерфейс ISignProvider под необходимую криптографию и указать его в EsiaOptions.SignProvider. Можно еще просто отключить эту проверку и не писать свой провайдер, поставить параметр VerifyTokenSignature в false

Я сейчас занимаюсь вопросом ГОСТ и в дальнейшем эта часть будет переделана

**Comment by tihomirov71** [comment]
Криптография отдельная часть библиотеки и ее можно заменить. Сейчас достаточно вернуть нужный сертификат (ГОСТ или любой другой), то есть для формирования подписи при обращении к ЕСИА этого достаточно (как в примере в документации).
Это не работает. При подстановке сертификата ГОСТ2012 выдает ошибку при формировании подписи
Could not determine signature algorithm for the signer certificate.

**Comment by xeltan** [comment]
В библиотеке используется стандартные средства Windows для криптографии. Но у вас на системе должно стоять специализированное ПО для ГОСТ криптографии, например КриптоПРО.
Сама Windows не поддерживает ГОСТ криптографию, но дает универсальное API для работы с криптографией. У меня например, стоит КриптоПРО и все работает без каких-либо переделок библиотеки.

**Comment by CryptorDy** [comment]
> В библиотеке используется стандартные средства Windows для криптографии. Но у вас на системе должно стоять специализированное ПО для ГОСТ криптографии, например КриптоПРО.
> Сама Windows не поддерживает ГОСТ криптографию, но дает универсальное API для работы с криптографией. У меня например, стоит КриптоПРО и все работает без каких-либо переделок библиотеки.

Вы просто установили КриптоПро и все? У меня такая же проблема ( Could not determine signature algorithm for the signer certificate. ). Сертификат с производственной среды.

**Comment by CryptorDy** [comment]
Проблема выходит, когда вызываю var redirectUri = esiaClient.BuildRedirectUri();

**Comment by xeltan** [comment]
Support .NET Core 3.1
